name: CI/CD Pipline for dev ENV

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build . -t ${{ secrets.NEW_DOCKER_USERNAME }}/mostachari_backend:latest

    - name: Push Docker image to Docker Hub
      run: |
        echo "$NEW_DOCKER_PASSWORD" | docker login -u "$NEW_DOCKER_USERNAME" --password-stdin
        docker push ${{ secrets.NEW_DOCKER_USERNAME }}/mostachari_backend:latest

    - name: SSH and Deploy to DigitalOcean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker pull ${{ secrets.NEW_DOCKER_USERNAME }}/mostachari_backend:latest
          docker stop myapp || true
          docker run -d --name myapp -p 80:80 ${{ secrets.NEW_DOCKER_USERNAME }}/mostachari_backend:latest
