name: PROD CI/CD Pipeline

on:
  push:
    branches:
      - prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Run tests
      #   run: pytest  # Assuming you have tests defined

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.NEW_DOCKER_USERNAME }}
          password: ${{ secrets.NEW_DOCKER_PASSWORD }}

      - name: Verify Docker Login
        run: docker info
        
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.NEW_DOCKER_USERNAME }}/mostachari_backend_prod:latest

      

      - name: SSH and Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP_PROD }}
          username: ${{ secrets.SERVER_USERNAME_PROD }}
          password: ${{ secrets.SERVER_PASSWORD_PROD }}
          script: |
            set -e  # Ensures the script stops on the first error
            docker login -u ${{ secrets.NEW_DOCKER_USERNAME }} -p ${{ secrets.NEW_DOCKER_PASSWORD }}
            docker pull ${{ secrets.NEW_DOCKER_USERNAME }}/mostachari_backend_prod:latest
            docker stop myapp || true  # Ignore errors if 'myapp' is not running
            docker rm myapp || true  # Ignore errors if 'myapp' does not exist
            docker run -d --restart unless-stopped --name myapp -p 80:80 ${{ secrets.NEW_DOCKER_USERNAME }}/mostachari_backend_prod:latest
